site_name: Machine Learning
theme: readthedocs
# repo_name: gramandha/gramandha-docs
repo_url: https://github.com/gramandha/data-docs
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
nav:
  Tugas: LKM1.md
  

